/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SnacksMachine;

/**
 *
 * @author leuri
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        onejButton2 = new javax.swing.JButton();
        twojButton2 = new javax.swing.JButton();
        treejButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        menujPanel = new javax.swing.JPanel();
        visorjLabel = new javax.swing.JLabel();
        OnejButton = new javax.swing.JButton();
        TwojButton = new javax.swing.JButton();
        ThreejButton = new javax.swing.JButton();
        FivejButton = new javax.swing.JButton();
        SixjButton = new javax.swing.JButton();
        FourjButton = new javax.swing.JButton();
        EightjButton = new javax.swing.JButton();
        NinejButton = new javax.swing.JButton();
        SevenjButton = new javax.swing.JButton();
        ZerojButton = new javax.swing.JButton();
        SendjButton = new javax.swing.JButton();
        CanceljButton = new javax.swing.JButton();
        MoneyjButton = new javax.swing.JButton();
        CardjButton = new javax.swing.JButton();
        dispenserjButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        CocajButton = new javax.swing.JButton();
        PepsijButton = new javax.swing.JButton();
        SpritejButton = new javax.swing.JButton();
        DoritosjButton = new javax.swing.JButton();
        RufflesjButton = new javax.swing.JButton();
        FandangosjButton = new javax.swing.JButton();
        MentosjButton = new javax.swing.JButton();
        FinijButton = new javax.swing.JButton();
        AguajButton = new javax.swing.JButton();
        SnickersjButton = new javax.swing.JButton();
        BisjButton = new javax.swing.JButton();
        MmsjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        onejButton2.setText("1");

        twojButton2.setText("2");

        treejButton2.setText("3");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("003");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("002");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("001");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snacks Machine");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(248, 245, 245));
        jPanel2.setForeground(new java.awt.Color(232, 232, 255));

        menujPanel.setBackground(new java.awt.Color(240, 238, 238));
        menujPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENU", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 153, 255))); // NOI18N

        visorjLabel.setBackground(new java.awt.Color(255, 255, 255));
        visorjLabel.setToolTipText("");
        visorjLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        visorjLabel.setName(""); // NOI18N

        OnejButton.setBackground(new java.awt.Color(51, 153, 255));
        OnejButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        OnejButton.setForeground(new java.awt.Color(255, 255, 255));
        OnejButton.setText("1");
        OnejButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 238, 238), 1, true));
        OnejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnejButtonMouseClicked(evt);
            }
        });

        TwojButton.setBackground(new java.awt.Color(51, 153, 255));
        TwojButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TwojButton.setForeground(new java.awt.Color(255, 255, 255));
        TwojButton.setText("2");
        TwojButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 238, 238), 1, true));
        TwojButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TwojButtonMouseClicked(evt);
            }
        });

        ThreejButton.setBackground(new java.awt.Color(51, 153, 255));
        ThreejButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ThreejButton.setForeground(new java.awt.Color(255, 255, 255));
        ThreejButton.setText("3");
        ThreejButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 238, 238), 1, true));
        ThreejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThreejButtonMouseClicked(evt);
            }
        });
        ThreejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        FivejButton.setBackground(new java.awt.Color(51, 153, 255));
        FivejButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        FivejButton.setForeground(new java.awt.Color(255, 255, 255));
        FivejButton.setText("5");
        FivejButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 238, 238), 1, true));
        FivejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FivejButtonMouseClicked(evt);
            }
        });

        SixjButton.setBackground(new java.awt.Color(51, 153, 255));
        SixjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SixjButton.setForeground(new java.awt.Color(255, 255, 255));
        SixjButton.setText("6");
        SixjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 238, 238), 1, true));
        SixjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SixjButtonMouseClicked(evt);
            }
        });

        FourjButton.setBackground(new java.awt.Color(51, 153, 255));
        FourjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        FourjButton.setForeground(new java.awt.Color(255, 255, 255));
        FourjButton.setText("4");
        FourjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 238, 238), 1, true));
        FourjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FourjButtonMouseClicked(evt);
            }
        });

        EightjButton.setBackground(new java.awt.Color(51, 153, 255));
        EightjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EightjButton.setForeground(new java.awt.Color(255, 255, 255));
        EightjButton.setText("8");
        EightjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 238, 238), 1, true));
        EightjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EightjButtonMouseClicked(evt);
            }
        });

        NinejButton.setBackground(new java.awt.Color(51, 153, 255));
        NinejButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NinejButton.setForeground(new java.awt.Color(255, 255, 255));
        NinejButton.setText("9");
        NinejButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 238, 238), 1, true));
        NinejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NinejButtonMouseClicked(evt);
            }
        });

        SevenjButton.setBackground(new java.awt.Color(51, 153, 255));
        SevenjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SevenjButton.setForeground(new java.awt.Color(255, 255, 255));
        SevenjButton.setText("7");
        SevenjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 238, 238), 1, true));
        SevenjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SevenjButtonMouseClicked(evt);
            }
        });

        ZerojButton.setBackground(new java.awt.Color(51, 153, 255));
        ZerojButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ZerojButton.setForeground(new java.awt.Color(255, 255, 255));
        ZerojButton.setText("0");
        ZerojButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 238, 238), 1, true));
        ZerojButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZerojButtonMouseClicked(evt);
            }
        });

        SendjButton.setBackground(new java.awt.Color(51, 153, 255));
        SendjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SendjButton.setForeground(new java.awt.Color(255, 255, 255));
        SendjButton.setText("Ok");
        SendjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 238, 238), 1, true));

        CanceljButton.setBackground(new java.awt.Color(51, 153, 255));
        CanceljButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CanceljButton.setForeground(new java.awt.Color(255, 255, 255));
        CanceljButton.setText("X");
        CanceljButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 238, 238), 1, true));
        CanceljButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CanceljButtonMouseClicked(evt);
            }
        });

        MoneyjButton.setBackground(new java.awt.Color(240, 238, 238));
        MoneyjButton.setForeground(new java.awt.Color(51, 153, 255));
        MoneyjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SnacksMachine/notes.png"))); // NOI18N
        MoneyjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 238, 238), 1, true));

        CardjButton.setBackground(new java.awt.Color(240, 238, 238));
        CardjButton.setForeground(new java.awt.Color(51, 153, 255));
        CardjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SnacksMachine/credit-card.png"))); // NOI18N
        CardjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 238, 238), 1, true));

        javax.swing.GroupLayout menujPanelLayout = new javax.swing.GroupLayout(menujPanel);
        menujPanel.setLayout(menujPanelLayout);
        menujPanelLayout.setHorizontalGroup(
            menujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menujPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visorjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menujPanelLayout.createSequentialGroup()
                        .addComponent(OnejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(TwojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(ThreejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menujPanelLayout.createSequentialGroup()
                        .addComponent(FourjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FivejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SixjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menujPanelLayout.createSequentialGroup()
                        .addComponent(SevenjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EightjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NinejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menujPanelLayout.createSequentialGroup()
                        .addComponent(CanceljButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ZerojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SendjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MoneyjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CardjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menujPanelLayout.setVerticalGroup(
            menujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menujPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visorjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(menujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(OnejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TwojButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ThreejButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(menujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(FourjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FivejButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SixjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(menujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SevenjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(EightjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NinejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(menujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(CanceljButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZerojButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SendjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(MoneyjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CardjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276))
        );

        dispenserjButton.setBackground(new java.awt.Color(0, 0, 0));
        dispenserjButton.setToolTipText("");
        dispenserjButton.setBorder(null);

        jPanel4.setLayout(new java.awt.CardLayout());

        CocajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SnacksMachine/Coca-Cola-Can-icon.png"))); // NOI18N

        PepsijButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SnacksMachine/Pepsi.png"))); // NOI18N

        SpritejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SnacksMachine/Sprite.png"))); // NOI18N

        DoritosjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SnacksMachine/Doritos.png"))); // NOI18N

        RufflesjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SnacksMachine/Rufles.png"))); // NOI18N

        FandangosjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SnacksMachine/Fandangos.png"))); // NOI18N

        MentosjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SnacksMachine/mentos.png"))); // NOI18N

        FinijButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SnacksMachine/fini.png"))); // NOI18N

        AguajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SnacksMachine/Agua.png"))); // NOI18N

        SnickersjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SnacksMachine/Snickers.png"))); // NOI18N

        BisjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SnacksMachine/bis.png"))); // NOI18N

        MmsjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SnacksMachine/mms.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("R$ 4,00");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("R$ 4,00");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("R$ 4,00");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("R$ 7,00");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("R$ 7,00");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("R$ 5,00");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("R$ 3,00");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("R$ 3,00");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("R$ 3,00");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("R$ 3,00");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("R$ 3,00");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("R$ 7,00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CocajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DoritosjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MentosjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BisjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel1)))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(PepsijButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RufflesjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FinijButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SnickersjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FandangosjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AguajButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(11, 11, 11))
                                    .addComponent(SpritejButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(MmsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(8, 8, 8))
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(13, 13, 13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(dispenserjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(menujPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CocajButton)
                            .addComponent(PepsijButton)
                            .addComponent(SpritejButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoritosjButton)
                    .addComponent(RufflesjButton)
                    .addComponent(FandangosjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MentosjButton)
                    .addComponent(FinijButton)
                    .addComponent(AguajButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SnickersjButton)
                    .addComponent(BisjButton)
                    .addComponent(MmsjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dispenserjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(menujPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void OnejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnejButtonMouseClicked
        // TODO add your handling code here:
        String valor = visorjLabel.getText();
        visorjLabel.setText(valor + "1");
    }//GEN-LAST:event_OnejButtonMouseClicked

    private void TwojButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TwojButtonMouseClicked
        // TODO add your handling code here:
        String valor = visorjLabel.getText();
        visorjLabel.setText(valor + "2");
    }//GEN-LAST:event_TwojButtonMouseClicked

    private void ThreejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThreejButtonMouseClicked
        // TODO add your handling code here:
        String valor = visorjLabel.getText();
        visorjLabel.setText(valor + "3");
    }//GEN-LAST:event_ThreejButtonMouseClicked

    private void FourjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FourjButtonMouseClicked
        // TODO add your handling code here:
        String valor = visorjLabel.getText();
        visorjLabel.setText(valor + "4");
    }//GEN-LAST:event_FourjButtonMouseClicked

    private void FivejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FivejButtonMouseClicked
        // TODO add your handling code here:
        String valor = visorjLabel.getText();
        visorjLabel.setText(valor + "5");
    }//GEN-LAST:event_FivejButtonMouseClicked

    private void SixjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SixjButtonMouseClicked
        // TODO add your handling code here:
         String valor = visorjLabel.getText();
        visorjLabel.setText(valor + "6");
    }//GEN-LAST:event_SixjButtonMouseClicked

    private void SevenjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SevenjButtonMouseClicked
        // TODO add your handling code here:
        String valor = visorjLabel.getText();
        visorjLabel.setText(valor + "7");
    }//GEN-LAST:event_SevenjButtonMouseClicked

    private void EightjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EightjButtonMouseClicked
        // TODO add your handling code here:
        String valor = visorjLabel.getText();
        visorjLabel.setText(valor + "8");
    }//GEN-LAST:event_EightjButtonMouseClicked

    private void NinejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NinejButtonMouseClicked
        // TODO add your handling code here:
        String valor = visorjLabel.getText();
        visorjLabel.setText(valor + "9");
    }//GEN-LAST:event_NinejButtonMouseClicked

    private void ZerojButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZerojButtonMouseClicked
        // TODO add your handling code here:
        String valor = visorjLabel.getText();
        visorjLabel.setText(valor + "0");
    }//GEN-LAST:event_ZerojButtonMouseClicked

    private void CanceljButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CanceljButtonMouseClicked
        // TODO add your handling code here:
        String valor = visorjLabel.getText();
        visorjLabel.setText("");
    }//GEN-LAST:event_CanceljButtonMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AguajButton;
    private javax.swing.JButton BisjButton;
    private javax.swing.JButton CanceljButton;
    private javax.swing.JButton CardjButton;
    private javax.swing.JButton CocajButton;
    private javax.swing.JButton DoritosjButton;
    private javax.swing.JButton EightjButton;
    private javax.swing.JButton FandangosjButton;
    private javax.swing.JButton FinijButton;
    private javax.swing.JButton FivejButton;
    private javax.swing.JButton FourjButton;
    private javax.swing.JButton MentosjButton;
    private javax.swing.JButton MmsjButton;
    private javax.swing.JButton MoneyjButton;
    private javax.swing.JButton NinejButton;
    private javax.swing.JButton OnejButton;
    private javax.swing.JButton PepsijButton;
    private javax.swing.JButton RufflesjButton;
    private javax.swing.JButton SendjButton;
    private javax.swing.JButton SevenjButton;
    private javax.swing.JButton SixjButton;
    private javax.swing.JButton SnickersjButton;
    private javax.swing.JButton SpritejButton;
    private javax.swing.JButton ThreejButton;
    private javax.swing.JButton TwojButton;
    private javax.swing.JButton ZerojButton;
    private javax.swing.JButton dispenserjButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel menujPanel;
    private javax.swing.JButton onejButton2;
    private javax.swing.JButton treejButton2;
    private javax.swing.JButton twojButton2;
    private javax.swing.JLabel visorjLabel;
    // End of variables declaration//GEN-END:variables
}
